import logging

MONGODB_HOSTNAME = "localhost"
MONGODB_PORT = 27017

DATABASE_NAME = "designerdrugdatabase"

LOGGING_LEVEL = logging.INFO

FIX_SUBSTANCES = True
CPU_CORES = 4

FORMAT_EXPORT = True
EXPORT_ONLY_FROM_CAYMANCHEM = True

